2024-11-27 12:30:43,066 | WARNING | Неверный тип данных для объекта Runner: Имя может быть только строкой, передано int
Traceback (most recent call last):
  File "D:\PythonProjectUni\Module_12\pr_12_4_log.py", line 79, in test_run
    runner = Runner(2)
             ^^^^^^^^^
  File "D:\PythonProjectUni\Module_12\pr_12_4_log.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-11-27 12:30:43,067 | WARNING | Неверная скорость для Runner: Скорость не может быть отрицательной, сейчас -5
Traceback (most recent call last):
  File "D:\PythonProjectUni\Module_12\pr_12_4_log.py", line 68, in test_walk
    walker = Runner('Walker', -5)
             ^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonProjectUni\Module_12\pr_12_4_log.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
